FROM   oven/bun:1-alpine 
ARG    DATABASE_URL
WORKDIR /app
COPY  . .
RUN   bun install
RUN   bun run db:generate
RUN   DATABASE=${DATABASE_URL} bun run build
EXPOSE 3003
CMD  ["bun", "run", "start:web"]