FROM oven/bun:1-alpine

ARG DATABASE_URL

WORKDIR /app

# Copy only dependency files first
COPY package.json ./

COPY apps/web/package.json ./apps/web/package.json
COPY packages ./packages
# Install dependencies
RUN bun install

# Copy remaining files
COPY . .

# Generate prisma client
RUN bun run db:generate

# Build app
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3003

CMD ["bun", "run", "start:web"]