FROM oven/bun:1-alpine 

WORKDIR /app

COPY package.json ./

RUN bun install 

COPY . .

# RUN bunx prisma migrate dev --name initial-schema
RUN bunx prisma generate 

EXPOSE 3000

# Run the app
CMD bunx prisma migrate deploy && bun run src/index.ts
