FROM oven/bun:1-alpine 

WORKDIR /app

COPY package.json ./

RUN bun install 

COPY . .

RUN bunx prisma migrate
RUN bunx prisma generate 

EXPOSE 3000

# Run the app
CMD ["bun", "run", "src/index.ts"]
