# Build the docker image
# Push the docker image to docker hub
# ssh into our VM and start the new image 

name: Continuous deploy 
on:
  branchs: [ main ]

jobs:
  build:
    runs_on: ubuntu-latest
    
